[package]
name = "haberdashery-asm-gen"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1

[features]
asm_gen =[]
haswell = ["asm_gen", "aes"]
broadwell = ["asm_gen", "aes"]
skylake = ["asm_gen", "aes"]
skylakex = ["asm_gen", "aes", "avx512f", "avx512vl", "avx512bw"]
tigerlake = ["asm_gen", "aes", "avx512f", "avx512vl", "avx512bw", "vpclmulqdq"]

# features
aes = []
avx512f = []
avx512vl = []
avx512bw = []
vpclmulqdq = []

# x25519 rfc test vectors take a particularly long time
very_long_tests = []

[dependencies]
cpuid = { path = "../cpuid" }
intrinsics = { path = "../intrinsics" }

[build-dependencies]
version_check = "0.9.4"

[dev-dependencies]
aes-gcm = "0.10.2"
aes-gcm-siv = "0.11.1"
generic-array = "0.14.7"
hex = "0.4.3"
hex-literal = "0.4.1"
hex2 = { package = "hex", path = "../hex" }
random = { path = "../random" }
static-env = { path = "../static-env" }
test-vectors = { path = "../test-vectors" }
