[package]
name = "gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
convert_case = "0.6.0"
hex = "0.4.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
sflags = { path = "../../sflags" }
