[package]
name = "aws-lc-benchmarks"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[[bench]]
name = "bench"
harness = false

[dev-dependencies]
hex = "0.4.3"

[dependencies]
aws-lc-sys = "0.23.1"
perf-caliper = { path = "../perf-caliper" }
